const GET_SHOWINFO="GET_SHOWINFO";
const GET_SHOWINFOTOURCITY="GET_SHOWINFOTOURCITY";
const GET_SHOWINFOLIST = "GET_SHOWINFOLIST";
export default {
    GET_SHOWINFO,
    GET_SHOWINFOTOURCITY,
    GET_SHOWINFOLIST
}