const GET_SHOWINFO="GET_SHOWINFO";
const GET_SHOWINFOTOURCITY="GET_SHOWINFOTOURCITY";
const GET_SHOWINFOLIST = "GET_SHOWINFOLIST";
const GET_HOMESWIDERLIST = "GET_HOMESWIDERLIST";
export default {
    GET_SHOWINFO,
    GET_SHOWINFOTOURCITY,
    GET_SHOWINFOLIST,
    GET_HOMESWIDERLIST
}